name: terraform-k8s

on:
  pull_request:
    paths: ["infra/terraform/**"]
  push:
    branches: ["main"]
    paths: ["infra/terraform/**"]

jobs:
  tf:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: infra/terraform

    steps:
      - uses: actions/checkout@v4

      # - name: Terraform Init
      #   run: terraform init
      #
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
