name: terraform-k8s

on:
  pull_request:
    paths: ["infra/terraform/**"]
  push:
    branches: ["main"]
    paths: ["infra/terraform/**"]

jobs:
  tf:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: infra/terraform

    steps:
      - uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Import (bootstrap)
        if: github.event_name == 'push'
        run: |
          terraform import kubernetes_deployment.recommendations default/recommendations || true
          terraform import kubernetes_service.recommendations default/recommendations || true
          terraform import kubernetes_deployment.marketplace default/marketplace || true
          terraform import kubernetes_service.marketplace default/marketplace || true
          terraform import kubernetes_namespace.tfdrift-operator tfdrift-operator-system || true
          terraform import kubernetes_cluster_role.tfdrift-operator tfdrift-operator || true
          terraform import kubernetes_service_account.tfdrift-operator tfdrift-operator-system/tfdrift-operator || true
          terraform import kubernetes_cluster_role_binding.tfdrift-operator tfdrift-operator || true
          terraform import kubernetes_deployment.tfdrift-operator tfdrift-operator-system/tfdrift-operator || true

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
